"""initial schema

Revision ID: 5c0cdbd880ff
Revises: 
Create Date: 2026-06-21 20:20:06.862359

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0cdbd880ff'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connection_label', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('repo_id', sa.String(length=128), nullable=False),
    sa.Column('check_label', sa.String(length=128), nullable=False),
    sa.Column('result', sa.String(length=256), nullable=False),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('provider_type', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('auth_mode', sa.String(length=128), nullable=False),
    sa.Column('credential_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('granted_capabilities', sa.JSON(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediations',
    sa.Column('repo_id', sa.String(length=128), nullable=False),
    sa.Column('check_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('repo_id', 'check_id')
    )
    op.create_table('repos',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.String(length=64), nullable=False),
    sa.Column('open_prs', sa.Integer(), nullable=False),
    sa.Column('dependabot_prs', sa.Integer(), nullable=False),
    sa.Column('ci_status', sa.String(length=8), nullable=False),
    sa.Column('alerts', sa.JSON(), nullable=False),
    sa.Column('release_pending_days', sa.Integer(), nullable=True),
    sa.Column('fails', sa.JSON(), nullable=False),
    sa.Column('unknowns', sa.JSON(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'connection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repos')
    op.drop_table('remediations')
    op.drop_table('policy')
    op.drop_table('connections')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
