/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness (Constitution VI). Unauthenticated. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            /** @enum {string} */
                            access_mode?: "forward-auth" | "oidc" | "disabled";
                            connections: {
                                id?: string;
                                /** Format: date-time */
                                last_sync_at?: string;
                                stale?: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolved operator identity + access mode (drives sidebar access badge). Gated. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description proxy/OIDC identity */
                            actor: string;
                            /** @enum {string} */
                            access_mode: "forward-auth" | "oidc" | "disabled";
                            /** @example Remote-User */
                            user_header?: string;
                            /** @example /auth/login */
                            login_url?: string;
                            /** @example /auth/logout */
                            logout_url?: string;
                        };
                    };
                };
                /** @description No session (oidc mode */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public pre-login probe — lets the SPA decide whether to show the login screen.
         * @description Unauthenticated and exempt from the access-control middleware. In oidc mode reports whether a valid session exists; in forward-auth/disabled mode always authenticated.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            mode: "forward-auth" | "oidc" | "disabled";
                            authenticated: boolean;
                            actor?: string | null;
                            /** @example /auth/login */
                            login_url: string;
                            /** @example /auth/logout */
                            logout_url: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the OIDC session (best-effort RP-initiated IdP logout when configured). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                /** @description Redirect to the IdP end-session endpoint */
                303: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fleet/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fleet overview screen — stat tiles, repo table, attention feed (FR-001–FR-004). */
        get: {
            parameters: {
                query?: {
                    /** @description Filter the fleet to one connection id, or "all" (FR-004). */
                    connection?: components["parameters"]["Connection"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            summary: {
                                repo_count?: number;
                                compliance_pct?: number;
                                /** @example 2m ago */
                                synced?: string;
                                /** @description repos with failing default-branch CI */
                                ci_failing?: number;
                                /** @description total critical security alerts */
                                critical_alerts?: number;
                            };
                            /** @description six tiles — Open PRs, Bot PRs, CI failing, Sec alerts, Release pending, Compliance */
                            stats: {
                                label?: string;
                                value?: string;
                                sub?: string;
                                tone?: components["schemas"]["Tone"];
                                sub_tone?: components["schemas"]["Tone"];
                            }[];
                            repos: components["schemas"]["RepoRow"][];
                            /** @description needs-attention items sorted by urgency (critical→CI→release→alerts→bot PRs) */
                            feed: {
                                tag?: string;
                                title?: string;
                                repo_id?: string;
                                /** @description owning connection — for connection-scoped drill-in */
                                connection_id?: string;
                                tone?: components["schemas"]["Tone"];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fleet/scorecard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hygiene scorecard matrix + roll-up (FR-005–FR-007). */
        get: {
            parameters: {
                query?: {
                    /** @description Filter the fleet to one connection id, or "all" (FR-004). */
                    connection?: components["parameters"]["Connection"];
                    failing_only?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            compliance_pct: number;
                            clear_count?: number;
                            repo_count?: number;
                            groups?: {
                                label?: string;
                                span?: number;
                            }[];
                            checks: {
                                id?: string;
                                label?: string;
                                fail_count?: number;
                            }[];
                            rows: {
                                repo_id?: string;
                                /** @description owning connection — for connection-scoped drill-in */
                                connection_id?: string;
                                hygiene_pct?: number;
                                connection_badge?: string;
                                cells?: components["schemas"]["FindingStatus"][];
                            }[];
                            /** @description top drift — checks with most failures */
                            rollup: {
                                label?: string;
                                count?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check catalog grouped, with current policy enablement, targets, and pass rates (FR-008, FR-009, FR-019). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            enabled_count?: number;
                            total_count?: number;
                            groups?: {
                                group?: string;
                                checks?: components["schemas"]["CatalogCheck"][];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The single fleet-wide policy (FR-019). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Policy"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle a check or set a target; scorecard recomputes (FR-019). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        check_id?: string;
                        enabled?: boolean;
                        /**
                         * @example {
                         *       "target": 7
                         *     }
                         */
                        params?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Policy"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connection cards + access banner state (FR-021–FR-026, FR-027–FR-032). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access?: {
                                /** @enum {string} */
                                mode?: "forward-auth" | "disabled";
                                user_header?: string;
                                allowed_user?: string | null;
                                fail_closed?: boolean;
                            };
                            connections?: components["schemas"]["ConnectionCard"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add a provider connection — configuration, not code (FR-024, SC-004). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        provider_type: "github" | "gitea";
                        label: string;
                        scope: string;
                        /** @description write-only; GitHub App private-key PEM or a PAT/token. Encrypted at rest (FR-032) */
                        credential?: string;
                        /** @description reuse another same-provider connection's stored credential instead of pasting one again */
                        copy_credential_from?: string | null;
                        /** @description GitHub App id (App connections only) */
                        app_id?: string | null;
                        /** @description GitHub App installation id (App connections only) */
                        installation_id?: number | null;
                        /**
                         * @description grant write tiers only if the credential can write (least-privilege
                         * @default false
                         */
                        writable?: boolean;
                        /** @description write-only; per-connection inbound-webhook HMAC secret. Encrypted at rest; falls back to the global secret when omitted (FR-033) */
                        webhook_secret?: string;
                        /** @description org/user that owns the repos; defaults to the label suffix when omitted */
                        owner?: string;
                        /** @description repo names to watch; omit/null ⇒ watch every repo the credential can see */
                        repo_allowlist?: string[] | null;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectionCard"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a connection — drops its repos/findings/snapshots; audit entries retained (clarification). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    connection_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{connection_id}/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repos the connection's credential can see, plus the current allowlist selection.
         * @description Explicit management action (the repo picker) — unlike dashboard reads this makes a live provider call to enumerate candidates. selected=null ⇒ watching all.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    connection_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            connection_id?: string;
                            owner?: string;
                            available?: {
                                name: string;
                                /** @description repo visibility on the provider */
                                private: boolean;
                            }[];
                            selected?: string[] | null;
                            watching_all?: boolean;
                        };
                    };
                };
                /** @description Unknown connection */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Provider could not list repos */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Replace the connection's repo allowlist; prunes de-selected snapshots and resyncs. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    connection_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description repo names to watch; null/empty ⇒ watch all */
                        repos?: string[] | null;
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectionCard"];
                    };
                };
                /** @description Unknown connection */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually refresh every connection now (operator-triggered re-interrogation).
         * @description Enqueues an immediate background re-interrogation of all connections — the same path as the scheduled poll, so reads stay cache-served and the request never blocks on the provider. The dashboard reflects the result once the sync lands (202 Accepted).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncAccepted"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{connection_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually refresh one connection now (operator-triggered re-interrogation). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    connection_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncAccepted"];
                    };
                };
                /** @description Unknown connection */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log — every correction, immutable (FR-016). */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{connection_id}/{repo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Repo drill-down — activity strip + grouped policy checks with remediation controls (Story 3).
         * @description A repo is addressed by (connection_id, repo_id); resolving by repo_id alone is forbidden because same-named repos can exist under different connections (Constitution I).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    connection_id: string;
                    repo_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RepoDetail"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{connection_id}/{repo_id}/checks/{check_id}/remediate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Human-triggered remediation (FR-011–FR-018). kind=settings_patch applies a scoped change; kind=config_pr opens a PR (never push/force-push, FR-014); deep_link/report are recorded only. Idempotent: an existing open Hangar PR is surfaced, not duplicated (FR-015). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    connection_id: string;
                    repo_id: string;
                    check_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        kind: "report" | "deep_link" | "settings_patch" | "config_pr";
                    };
                };
            };
            responses: {
                /** @description Result of the correction */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            state?: "working" | "pr_open" | "fixed" | "deep_link";
                            pr_url?: string | null;
                            audit?: components["schemas"]["AuditEntry"];
                            /** @description true if an existing open PR was surfaced (FR-015) */
                            idempotent_hit?: boolean;
                        };
                    };
                };
                /** @description Connection lacks write scope — collapses to deep-link (FR-018) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deep_link_url?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{connection_id}/{repo_id}/checks/{check_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a Hangar-authored PR merged — the finding flips to pass and the merge is audited (prototype markMerged; FR-005a, FR-016). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    connection_id: string;
                    repo_id: string;
                    check_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Finding flipped to pass */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            state?: "fixed";
                            pr_url?: string | null;
                            idempotent_hit?: boolean;
                        };
                    };
                };
                /** @description No open Hangar PR exists for this check, so there is nothing to mark merged (prevents fabricating a 'PR merged' pass + audit entry, FR-016). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks/{check_id}/remediate-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fleet-wide remediation — apply one check's correction across many repos in a single operator action (PR-first, idempotent, one audit entry per repo; read-only connections collapse to a deep-link). The kind is resolved server-side. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    check_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        targets: {
                            connection_id: string;
                            repo_id: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Per-target outcomes + a status roll-up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            check_id?: string;
                            /** @description count of targets per outcome status */
                            summary?: {
                                [key: string]: number;
                            };
                            results?: {
                                connection_id?: string;
                                repo_id?: string;
                                /** @enum {string} */
                                status?: "pr_open" | "fixed" | "deep_link" | "not_found" | "error";
                                pr_url?: string | null;
                                deep_link_url?: string | null;
                                idempotent_hit?: boolean;
                                detail?: string | null;
                            }[];
                        };
                    };
                };
                /** @description Unknown check */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description status-only color token (maps to --pass/--warn/--fail/--unknown)
         * @enum {string}
         */
        Tone: "pass" | "warn" | "fail" | "unknown" | "neutral";
        /**
         * @description effective status incl. remediation overlay (FR-005, FR-005a)
         * @enum {string}
         */
        FindingStatus: "pass" | "fail" | "unknown" | "pending" | "working";
        RepoRow: {
            id?: string;
            /** @description owning connection — used to address the repo connection-scoped */
            connection_id?: string;
            connection_badge?: string;
            description?: string;
            open_prs?: number;
            dependabot_prs?: number;
            /** @enum {string} */
            ci?: "pass" | "fail" | "none";
            /** @description SPDX id of the detected license (e.g. MIT); null when absent/unidentifiable */
            license?: string | null;
            alerts_total?: number;
            alerts_tone?: components["schemas"]["Tone"];
            release_pending_days?: number | null;
            hygiene_pct?: number;
        };
        CatalogCheck: {
            id?: string;
            label?: string;
            /** @enum {string} */
            tier?: "patch" | "pr" | "link" | "report";
            /** @example API · PR */
            tier_label?: string;
            enabled?: boolean;
            has_target?: boolean;
            target?: number | null;
            pass_count?: number;
            repo_count?: number;
        };
        Policy: {
            id?: string;
            name?: string;
            entries?: {
                check_id?: string;
                enabled?: boolean;
                params?: {
                    [key: string]: unknown;
                };
                /** @enum {string} */
                severity?: "low" | "medium" | "high";
            }[];
        };
        ConnectionCard: {
            id?: string;
            label?: string;
            /** @enum {string} */
            type?: "GitHub" | "Gitea";
            /** @enum {string} */
            provider_type?: "github" | "gitea";
            /** @description whether a real credential is stored (reusable by another connection) */
            has_credential?: boolean;
            scope?: string;
            auth_mode?: string;
            repos?: number;
            writes?: boolean;
            /** @example Read + write */
            write_label?: string;
            /** @example API + PR + deep-link */
            remediation?: string;
            /** @description humanized last-sync time for display */
            synced?: string;
            /**
             * Format: date-time
             * @description machine-readable last successful sync (null if never); poll this to detect a refresh landing
             */
            last_sync_at?: string | null;
            /** @description operator's repo selection; null ⇒ watching all repos */
            repo_allowlist?: string[] | null;
        };
        SyncAccepted: {
            /** @example accepted */
            status: string;
            /** @description the refreshed connection; null for a fleet-wide refresh */
            connection_id?: string | null;
        };
        AuditEntry: {
            timestamp?: string;
            repo_id?: string;
            check_label?: string;
            connection_label?: string;
            actor?: string;
            result?: string;
            pr_url?: string | null;
        };
        RepoDetail: {
            id?: string;
            connection_label?: string;
            description?: string;
            read_only?: boolean;
            hygiene_pct?: number;
            /** @example 14/23 checks */
            pass_count?: string;
            open_prs?: number;
            /** @enum {string} */
            ci?: "pass" | "fail" | "none";
            pull_requests?: {
                title?: string;
                /** @enum {string} */
                kind?: "dependabot" | "human";
                /** @description human-display status (e.g. "open", "draft") */
                status?: string;
                status_tone?: components["schemas"]["Tone"];
                age?: string;
                /** @description link to the PR on the provider */
                url?: string | null;
            }[];
            alerts?: {
                severity?: string;
                count?: number;
            }[];
            check_groups?: {
                group?: string;
                checks?: {
                    id?: string;
                    label?: string;
                    status?: components["schemas"]["FindingStatus"];
                    /**
                     * @description structured remediation kind the client sends back (never parse the action label)
                     * @enum {string}
                     */
                    kind?: "report" | "deep_link" | "settings_patch" | "config_pr";
                    tier_label?: string;
                    evidence?: string;
                    open_pr_url?: string | null;
                    open_pr_number?: number | null;
                    /** @description display label only, e.g. Open fix PR | Enable | Open in GitHub */
                    primary_action?: string | null;
                    /** @example Mark merged */
                    secondary_action?: string | null;
                }[];
            }[];
        };
    };
    responses: never;
    parameters: {
        /** @description Filter the fleet to one connection id, or "all" (FR-004). */
        Connection: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
